# Generated by Django 4.2.2 on 2023-09-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cart_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
